
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: dinnyuy/petclinic:latest
          ports:
            - containerPort: 8080
            imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: petclinic-service 
spec:
  selector:
    app: petclinic 
  ports:
    - name: http
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
